name: Preparant per producciÃ³ back
run-name: ${{ github.actor }} estÃ  pujant l'aplicaciÃ³ a PROD LARAVELðŸš€

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ”„ Clonar el repositori
        uses: actions/checkout@v4

      - name: ðŸ› ï¸ Configurar PHP i Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, curl, gd, pdo_mysql, zip
          tools: composer:v2

      - name: ðŸ“¦ Instalar dependencias en el runner
        run: composer install --optimize-autoloader

      - name: ðŸ“‚ Sincronizar archivos con el servidor
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          rsync -avz --delete --exclude '.env' -e "ssh -o StrictHostKeyChecking=no -i ~/prod_key.pem" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/backend/laravel/
          rm ~/prod_key.pem

      - name: ðŸ“¦ Optimizar y migrar en el servidor
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /var/www/backend/laravel
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart php8.2-fpm
          EOF

      - name: âœ… Deploy exitÃ³s
        run: echo "ðŸ Deployment completat amb Ã¨xit!"

